### ISSUE TITLE
Perbarui API Daftar rumah sakit

### ISSUE THREAD

**Issue by satyawikananda** [satyawikananda/rs-bed-covid-indo-api#1]
Perbarui API dikarenakan website siranap mendesain ulang situs-nya.

**Comment by satyawikananda** [comment]
Perbaruan Bed Detail API #3

**Comment by hendraaagil** [comment]
Perbaikan data rumah sakit non-covid #5

**Comment by satyawikananda** [comment]
Aku ada sedikit perubahan, mungkin bisa di cek di commit ini [c1c76bf](https://github.com/satyawikananda/rs-bed-covid-indo-api/pull/5/commits/c1c76bfa567d5722cf5cf03e7f906a21f627a3bd)
@hendraaagil
