### ISSUE TITLE
Redundant Hospital Id 3403027 & 3403024

### ISSUE THREAD

**Issue by tentpoles** [satyawikananda/rs-bed-covid-indo-api#12]
https://rs-bed-covid-api.vercel.app/api/get-hospitals?provinceid=34prop&cityid=3403&type=1

**Comment by satyawikananda** [comment]
fixed on commit [0fa1628](https://github.com/satyawikananda/rs-bed-covid-indo-api/commit/0fa1628bd5e9074fa41cdaa48220967b0cb99fa1)
